### PR TITLE
Access to 2 properties

### PR DESCRIPTION
**Pull request by grzegorzociepka**
I've made it, beacuse accessing them is helpful when you want to support scroll with animation to selected tab.

### CODE REVIEW

**Comment by AndreiMisiukevich** [comment]
???

**Comment by AndreiMisiukevich** [comment]
How does it help?
BindableProperties should be readonly

These changes don't make sense

**Comment by grzegorzociepka** [comment]
So how can I close/open it on label click? 
With this changes I was able to do it by just changing these properties.

**Comment by AndreiMisiukevich** [comment]
@grzegorzociepka  https://github.com/AndreiMisiukevich/ExpandableView/blob/master/ExpandableView/ExpandableView.cs#L67-L68

Check release 1.0.5

**Comment by AndreiMisiukevich** [comment]
> So how can I close/open it on label click?
> With this changes I was able to do it by just changing these properties.

```Tapped += () => expandable.IsExpanded = !expandable.IsExpanded;```

**Comment by grzegorzociepka** [comment]
Oh ok, you did it new version, I was forking previous versions :)

**Comment by AndreiMisiukevich** [comment]
@grzegorzociepka anyway thanks for contribution :)

**Comment by grzegorzociepka** [comment]
If there is something that I can do in this project, tell me and I will try to that :)

**Comment by AndreiMisiukevich** [comment]
@grzegorzociepka you are welcome to any enhancements 
but i don't know what can we enhance..

**Comment by grzegorzociepka** [comment]
We can try to add 2 items in single view?
Something like this?
[https://i.imgur.com/jV8rcnN.png](url)

**Pull request closed without merging**
